-- 코드를 입력하세요
WITH MILK AS (
    SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
), YOGURT AS (
    SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'YOGURT'
)

SELECT YOGURT.CART_ID
FROM YOGURT INNER JOIN MILK ON YOGURT.CART_ID = MILK.CART_ID
ORDER BY YOGURT.CART_ID ASC;