-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS PRODUCT_CODE, 
P.PRICE * SUM(O.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE O INNER JOIN PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC