-- 코드를 입력하세요
WITH RENT AS (
    SELECT C.DAILY_FEE, C.CAR_TYPE, H.HISTORY_ID,
           DATEDIFF(end_date, start_date) + 1 AS RENTDAYS,
    CASE
      WHEN DATEDIFF(end_date, start_date) + 1 >= 90 THEN '90일 이상'
      WHEN DATEDIFF(end_date, start_date) + 1 >= 30 THEN '30일 이상'
      WHEN DATEDIFF(end_date, start_date) + 1 >= 7 THEN '7일 이상'
      ELSE 'NONE' END AS RENTDAYS_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    INNER JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT RENT.HISTORY_ID, 
ROUND(RENT.DAILY_FEE * RENT.RENTDAYS * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM RENT LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.DURATION_TYPE = RENT.RENTDAYS_TYPE AND P.CAR_TYPE = RENT.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
