-- 코드를 입력하세요
SELECT A.APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
INNER JOIN PATIENT P ON P.PT_NO = A.PT_NO
WHERE A.APNT_CNCL_YN = 'N' AND A.APNT_YMD LIKE '2022-04-13%' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;