-- 코드를 입력하세요
SELECT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;